# -*- coding: utf-8 -*-
"""01_excel_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-pBZsO6AVBC5m__iFR1PU3SqgOJLuNa
"""

# -*- coding: utf-8 -*-
"""01_excel_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5m15GgImxmLd-3RSYuri5Aj1YBPNvj7
"""

# ============================================
# 01_excel_ingestion.ipynb
# Reads supplier_prices.xlsx and exports clean raw data
# ============================================

import os
import pandas as pd
import json

# --- Setup shared project directory ---
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
os.makedirs(f"{PROJECT_ROOT}/data", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/output", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/quotations", exist_ok=True)

# --- Step 1: Excel file from data directory ---
excel_filename = f"{PROJECT_ROOT}/data/supplier_prices.xlsx"
if not os.path.exists(excel_filename):
    print(f"Error: Could not find {excel_filename}")
    exit(1)

# --- Step 2: Read the Excel file ---
supplier_df = pd.read_excel(excel_filename)
print(f"\n✅ Loaded {len(supplier_df)} rows from {excel_filename}")
print(f"Columns found: {list(supplier_df.columns)}")

# --- Step 3: Check expected columns are present ---
expected_cols = {"Material", "Specification", "Supplier", "Unit Price",
                  "Currency", "Unit", "Lead Time", "MOQ", "Available Stock"}
actual_cols = set(supplier_df.columns)
missing = expected_cols - actual_cols
extra = actual_cols - expected_cols

if missing:
    print(f"⚠️ Missing expected columns: {missing}")
if extra:
    print(f"ℹ️ Extra/unexpected columns found: {extra}")
if not missing:
    print("✅ All expected columns present")

# --- Step 4: Preview the data ---
print("\nFirst 5 rows:")
print(supplier_df.head())

print("\nNull value counts per column:")
print(supplier_df.isnull().sum())

print("\nRow count check:", "✅ ~30 rows as expected" if 25 <= len(supplier_df) <= 35
      else f"⚠️ Expected ~30 rows, got {len(supplier_df)}")

# --- Step 5: Basic dtype sanity check ---
if "Unit Price" in supplier_df.columns:
    non_numeric_prices = supplier_df[pd.to_numeric(supplier_df["Unit Price"], errors="coerce").isnull()]
    if len(non_numeric_prices) > 0:
        print(f"\n⚠️ {len(non_numeric_prices)} rows have non-numeric Unit Price:")
        print(non_numeric_prices)

# --- Step 6: Export raw data as JSON for downstream notebooks ---
supplier_records = supplier_df.to_dict(orient="records")

with open(f"{PROJECT_ROOT}/output/supplier_prices_raw.json", "w") as f:
    json.dump(supplier_records, f, indent=2, default=str)

print(f"\n✅ Saved {len(supplier_records)} supplier records to {PROJECT_ROOT}/output/supplier_prices_raw.json")