# -*- coding: utf-8 -*-
"""02_pdf_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-5hMyhy9b-gBN5_wUfF28Udf86nsmFq
"""

# -*- coding: utf-8 -*-
"""02_pdf_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/REPLACE_WITH_YOUR_COLAB_ID
"""

# ============================================
# 02_pdf_ingestion.ipynb
# Reads historical quotation PDFs and exports raw extracted data
# ============================================

import os
import re
import json

import pdfplumber

# --- Setup shared project directory ---
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
os.makedirs(f"{PROJECT_ROOT}/quotations", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/output", exist_ok=True)

# --- Step 1: Quotation PDFs directory ---
QUOTATIONS_DIR = f"{PROJECT_ROOT}/quotations"

existing_pdfs = [f for f in os.listdir(QUOTATIONS_DIR) if f.lower().endswith(".pdf")]

if not existing_pdfs:
    print("No PDFs found in quotations folder. Please place your quote PDFs there.")
    exit(1)

print(f"\n✅ Found {len(existing_pdfs)} PDF(s) in {QUOTATIONS_DIR}")
for f in existing_pdfs:
    print(f"   - {f}")

# --- Step 2: Field extraction patterns ---
# Each quotation is expected to contain labeled lines like:
#   Customer: Acme Engineering Pvt Ltd
#   Material: SS304 Sheet
#   Total Cost: INR 45,000
# Patterns are written to tolerate minor spacing/case differences.

FIELD_PATTERNS = {
    # Alternatives are ordered most-specific-first so a more precise label
    # (e.g. "Total Cost") wins over a looser one (e.g. "Total") when both
    # could technically match.
    "customer":        r"(?:Customer\s*Name|Bill\s*To|Client\s*Name|Client|Customer)\s*[:\-]\s*(.+)",
    "material":        r"Material\s*[:\-]\s*(.+)",
    "supplier":        r"Supplier\s*[:\-]\s*(.+)",
    "quantity":        r"Quantity\s*[:\-]\s*([\d,\.]+)\s*([A-Za-z]*)",
    "unit_price":      r"Unit\s*Price\s*[:\-]\s*([₹$€]?\s?[A-Za-z]{0,3}\.?\s?[\d,]+\.?\d*)",
    "currency":        r"Currency\s*[:\-]\s*([A-Za-z]{3})",
    "transportation":  r"Transport(?:ation)?\s*[:\-]\s*(.+)",
    "packaging":       r"Packaging\s*[:\-]\s*(.+)",
    "gst":             r"GST\s*[:\-]\s*([\d\.]+\s?%?)",
    "total_cost":      r"(?:Total\s*Cost|Grand\s*Total|Total\s*Amount|Net\s*Total|Total)\s*[:\-]\s*([₹$€]?\s?[A-Za-z]{0,3}\.?\s?[\d,]+\.?\d*)",
    "delivery_time":   r"Delivery\s*Time\s*[:\-]\s*(.+)"
}

DEBUG_MODE = False  # set True to print full raw text of every flagged PDF

REQUIRED_FIELDS = ["customer", "material", "supplier", "unit_price", "total_cost"]


def extract_text_from_pdf(pdf_path):
    """Extract all text from a PDF, page by page, joined into one string."""
    text_chunks = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text() or ""
            text_chunks.append(page_text)
    return "\n".join(text_chunks)


def extract_fields(text):
    """Run each field's regex against the full text and return a dict of raw matches."""
    record = {}
    for field, pattern in FIELD_PATTERNS.items():
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if not match:
            record[field] = None
            continue

        if field == "quantity":
            # captures a numeric part and an optional unit (e.g. "150", "kg")
            number, unit = match.group(1), match.group(2)
            record["quantity"] = number.strip()
            record["quantity_unit"] = unit.strip() if unit else None
        else:
            record[field] = match.group(1).strip()

    return record


# --- Step 3: Process every PDF ---
all_records = []
flagged_files = []

for filename in existing_pdfs:
    pdf_path = os.path.join(QUOTATIONS_DIR, filename)
    raw_text = extract_text_from_pdf(pdf_path)

    if not raw_text.strip():
        print(f"⚠️ {filename}: no extractable text (likely a scanned/image PDF)")
        flagged_files.append(filename)
        continue

    fields = extract_fields(raw_text)
    fields["source_file"] = filename

    missing_required = [f for f in REQUIRED_FIELDS if not fields.get(f)]
    if missing_required:
        print(f"⚠️ {filename}: missing required fields {missing_required}")
        flagged_files.append(filename)
        if DEBUG_MODE:
            print(f"--- Raw text for {filename} (for pattern debugging) ---")
            print(raw_text)
            print("--- end raw text ---\n")

    all_records.append(fields)

print(f"\n✅ Processed {len(all_records)} PDF(s), {len(flagged_files)} flagged for review")

# --- Step 4: Preview extracted records ---
print("\nSample extracted record:")
if all_records:
    print(json.dumps(all_records[0], indent=2, ensure_ascii=False))

print("\nField completeness across all records:")
for field in FIELD_PATTERNS.keys():
    filled = sum(1 for r in all_records if r.get(field))
    print(f"   {field:15s}: {filled}/{len(all_records)} filled")

# --- Step 5: Export raw extracted data as JSON for downstream notebooks ---
output_path = f"{PROJECT_ROOT}/output/quotations_raw.json"
with open(output_path, "w") as f:
    json.dump(all_records, f, indent=2, ensure_ascii=False)

print(f"\n✅ Saved {len(all_records)} quotation records to {output_path}")

if flagged_files:
    print(f"\n⚠️ Review these files before cleaning/validation step: {flagged_files}")