# -*- coding: utf-8 -*-
"""03_market_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wboKcin0WYE9FP9DmAueIkFibTrWiCpB
"""

# -*- coding: utf-8 -*-
"""03_market_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/REPLACE_WITH_YOUR_COLAB_ID
"""

# ============================================
# 03_market_api.ipynb
# Fetches live exchange rates and exports raw rate data
# ============================================

import os
import json
import requests
from datetime import datetime, timezone

# --- Setup shared project directory ---
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
os.makedirs(f"{PROJECT_ROOT}/output", exist_ok=True)

# --- Step 1: Configuration ---
# Base currency and the target currencies you need rates for.
# Add/remove target currencies here as your supplier/quotation data requires.
BASE_CURRENCY = "USD"
TARGET_CURRENCIES = ["INR", "EUR", "GBP"]

# Free, no-API-key exchange rate endpoint.
# Docs: https://www.exchangerate-api.com/docs/free
API_URL = f"https://open.er-api.com/v6/latest/{BASE_CURRENCY}"

# --- Step 2: Fetch live rates ---
print(f"Fetching exchange rates for base currency {BASE_CURRENCY}...")

try:
    response = requests.get(API_URL, timeout=10)
    response.raise_for_status()
    api_data = response.json()
except requests.exceptions.RequestException as e:
    raise SystemExit(f"❌ API request failed: {e}")

if api_data.get("result") != "success":
    raise SystemExit(f"❌ API returned an error: {api_data}")

print("✅ API call succeeded")

# --- Step 3: Extract and validate the rates we care about ---
all_rates = api_data.get("rates", {})
fetch_date = api_data.get("time_last_update_utc", datetime.now(timezone.utc).isoformat())

exchange_records = []
flagged_currencies = []

for target in TARGET_CURRENCIES:
    rate = all_rates.get(target)

    # Validation rules: rate exists, numeric, positive
    if rate is None:
        print(f"⚠️ No rate found for {BASE_CURRENCY} -> {target}")
        flagged_currencies.append(target)
        continue

    if not isinstance(rate, (int, float)):
        print(f"⚠️ Non-numeric rate for {BASE_CURRENCY} -> {target}: {rate}")
        flagged_currencies.append(target)
        continue

    if rate <= 0:
        print(f"⚠️ Non-positive rate for {BASE_CURRENCY} -> {target}: {rate}")
        flagged_currencies.append(target)
        continue

    exchange_records.append({
        "base_currency": BASE_CURRENCY,
        "target_currency": target,
        "exchange_rate": rate,
        "date": fetch_date,
    })

print(f"\n✅ Validated {len(exchange_records)}/{len(TARGET_CURRENCIES)} exchange rates")

# --- Step 4: Preview ---
print("\nExtracted rates:")
for rec in exchange_records:
    print(f"   1 {rec['base_currency']} = {rec['exchange_rate']} {rec['target_currency']}  (as of {rec['date']})")

if flagged_currencies:
    print(f"\n⚠️ Currencies that failed validation and were skipped: {flagged_currencies}")

# --- Step 5: Export raw rate data as JSON for downstream notebooks ---
output_path = f"{PROJECT_ROOT}/output/exchange_rates_raw.json"
with open(output_path, "w") as f:
    json.dump(exchange_records, f, indent=2, ensure_ascii=False)

print(f"\n✅ Saved {len(exchange_records)} exchange rate records to {output_path}")