# -*- coding: utf-8 -*-
"""04_clean_validate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OexI3P_va9Xbp1r35iCOJmqUsgnJ4nUy
"""

# -*- coding: utf-8 -*-
"""04_clean_validate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/REPLACE_WITH_YOUR_COLAB_ID
"""

# ============================================
# 04_clean_validate.ipynb
# Validates and cleans supplier, quotation, and exchange rate raw data
# ============================================

import os
import re
import json

# --- Setup shared project directory ---
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = f"{PROJECT_ROOT}/output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- Step 1: Load the three raw datasets produced by notebooks 1-3 ---
def load_json(filename):
    path = f"{OUTPUT_DIR}/{filename}"
    if not os.path.exists(path):
        raise SystemExit(f"❌ Required input not found: {path}\n"
                          f"   Run the earlier notebook that produces it first.")
    with open(path, "r") as f:
        return json.load(f)

supplier_raw = load_json("supplier_prices_raw.json")
quotations_raw = load_json("quotations_raw.json")
exchange_raw = load_json("exchange_rates_raw.json")

print(f"Loaded {len(supplier_raw)} supplier rows, "
      f"{len(quotations_raw)} quotation records, "
      f"{len(exchange_raw)} exchange rate records")

# ============================================================
# CLEANING HELPERS
# ============================================================

def clean_price(value):
    """
    Normalize a messy price string/number into a float.
    Handles: '₹820', '820 INR', 'Rs.820', 'INR 45,000', 45000, '45,000.50'
    Returns None if it cannot be parsed.
    """
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)

    text = str(value).strip()
    # Strip currency symbols/codes and thousands separators, keep digits and decimal point
    text = re.sub(r"[₹$€]", "", text)
    text = re.sub(r"\bRs\.?\b", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\b[A-Za-z]{3}\b", "", text)  # drop 3-letter currency codes like INR/USD
    text = text.replace(",", "").strip()
    text = re.sub(r"[^\d\.]", "", text)  # drop anything left that isn't a digit or dot

    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def clean_percentage(value):
    """Normalize a GST/percentage string like '18%' or '18' into a float (18.0)."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = re.sub(r"[^\d\.]", "", str(value))
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


# Known supplier name variants -> canonical name.
# Extend this map as you encounter new variants in your real data.
SUPPLIER_NAME_MAP = {
    "tata": "Tata Steel",
    "tata steel ltd": "Tata Steel",
    "tatasteel": "Tata Steel",
    "tata steel": "Tata Steel",
    "jsw": "JSW Steel",
    "jsw steel ltd": "JSW Steel",
    "jsw steel": "JSW Steel",
    "sail": "SAIL",
    "steel authority of india": "SAIL",
    "steel authority of india ltd": "SAIL",
}


def clean_supplier_name(value):
    """
    Normalize supplier name using a known-variant map first;
    fall back to simple title-casing for anything not in the map.
    """
    if not value:
        return None
    key = re.sub(r"[.\-]", "", str(value)).strip().lower()
    key = re.sub(r"\s+", " ", key)
    if key in SUPPLIER_NAME_MAP:
        return SUPPLIER_NAME_MAP[key]
    return str(value).strip().title()


MONTHS = {
    "jan": "01", "feb": "02", "mar": "03", "apr": "04", "may": "05", "jun": "06",
    "jul": "07", "aug": "08", "sep": "09", "oct": "10", "nov": "11", "dec": "12",
}


def clean_date(value):
    """
    Normalize common date formats into ISO 'YYYY-MM-DD'.
    Handles: '20 Jul 2026', '20/07/26', '2026-07-20', '20-07-2026'
    Returns None if it cannot be confidently parsed.
    """
    if not value:
        return None
    text = str(value).strip()

    # Already ISO
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", text)
    if m:
        return text

    # '20 Jul 2026' or '20 July 2026'
    m = re.match(r"^(\d{1,2})\s+([A-Za-z]{3,9})\s+(\d{4})$", text)
    if m:
        day, month_name, year = m.groups()
        month = MONTHS.get(month_name[:3].lower())
        if month:
            return f"{year}-{month}-{int(day):02d}"

    # '20/07/26' or '20-07-2026' or '20/07/2026' (assume DD/MM/YY[YY])
    m = re.match(r"^(\d{1,2})[/\-](\d{1,2})[/\-](\d{2,4})$", text)
    if m:
        day, month, year = m.groups()
        if len(year) == 2:
            year = "20" + year
        return f"{year}-{int(month):02d}-{int(day):02d}"

    return None  # unparseable — flagged during validation instead of guessed


def normalize_currency_code(value):
    if not value:
        return None
    code = str(value).strip().upper()
    return code if re.match(r"^[A-Z]{3}$", code) else None


# ============================================================
# STEP 2: SUPPLIER SHEET — validate + clean
# ============================================================
print("\n" + "=" * 50)
print("SUPPLIER PRICE SHEET")
print("=" * 50)

supplier_clean = []
supplier_invalid = []

for i, row in enumerate(supplier_raw):
    supplier_name = clean_supplier_name(row.get("Supplier"))
    currency = normalize_currency_code(row.get("Currency"))
    price = clean_price(row.get("Unit Price"))

    errors = []
    if not supplier_name:
        errors.append("missing supplier")
    if not currency:
        errors.append("invalid/missing currency")
    if price is None or price <= 0:
        errors.append("price not positive")

    if errors:
        supplier_invalid.append({"row_index": i, "errors": errors, "raw": row})
        continue

    supplier_clean.append({
        "material": str(row.get("Material", "")).strip(),
        "specification": str(row.get("Specification", "")).strip(),
        "supplier": supplier_name,
        "unit_price": price,
        "currency": currency,
        "unit": str(row.get("Unit", "")).strip(),
        "lead_time": row.get("Lead Time"),
        "moq": row.get("MOQ"),
        "available_stock": row.get("Available Stock"),
    })

print(f"✅ {len(supplier_clean)} valid rows, ⚠️ {len(supplier_invalid)} invalid rows")

# ============================================================
# STEP 3: HISTORICAL QUOTATIONS — validate + clean
# ============================================================
print("\n" + "=" * 50)
print("HISTORICAL QUOTATIONS")
print("=" * 50)

quotations_clean = []
quotations_invalid = []

for i, row in enumerate(quotations_raw):
    customer = str(row.get("customer") or "").strip()
    material = str(row.get("material") or "").strip()
    unit_price = clean_price(row.get("unit_price"))
    total_cost = clean_price(row.get("total_cost"))
    quantity_raw = clean_price(row.get("quantity"))
    currency = normalize_currency_code(row.get("currency")) or "INR"  # default assumption

    errors = []
    if not customer:
        errors.append("missing customer")
    if not material:
        errors.append("missing material")
    if unit_price is None or unit_price <= 0:
        errors.append("unit_price not positive")
    if quantity_raw is None or quantity_raw <= 0:
        errors.append("quantity not positive")

    if errors:
        quotations_invalid.append({
            "row_index": i,
            "source_file": row.get("source_file"),
            "errors": errors,
            "raw": row,
        })
        continue

    quotations_clean.append({
        "source_file": row.get("source_file"),
        "customer": customer,
        "material": material,
        "supplier": clean_supplier_name(row.get("supplier")),
        "quantity": quantity_raw,
        "quantity_unit": row.get("quantity_unit"),
        "unit_price": unit_price,
        "currency": currency,
        "transportation": clean_price(row.get("transportation")),
        "packaging": clean_price(row.get("packaging")),
        "gst_percent": clean_percentage(row.get("gst")),
        "total_cost": total_cost,
        "delivery_time": str(row.get("delivery_time") or "").strip(),
    })

print(f"✅ {len(quotations_clean)} valid records, ⚠️ {len(quotations_invalid)} invalid records")
if quotations_invalid:
    for item in quotations_invalid:
        print(f"   - {item['source_file']}: {item['errors']}")

# ============================================================
# STEP 4: EXCHANGE RATES — validate + clean
# ============================================================
print("\n" + "=" * 50)
print("EXCHANGE RATES")
print("=" * 50)

exchange_clean = []
exchange_invalid = []

for i, row in enumerate(exchange_raw):
    rate = row.get("exchange_rate")
    date = clean_date(row.get("date")) or row.get("date")  # keep original if unparseable

    errors = []
    if rate is None:
        errors.append("missing rate")
    elif not isinstance(rate, (int, float)):
        errors.append("rate not numeric")
    elif rate <= 0:
        errors.append("rate not positive")

    if errors:
        exchange_invalid.append({"row_index": i, "errors": errors, "raw": row})
        continue

    exchange_clean.append({
        "base_currency": row.get("base_currency"),
        "target_currency": row.get("target_currency"),
        "exchange_rate": float(rate),
        "date": date,
    })

print(f"✅ {len(exchange_clean)} valid rates, ⚠️ {len(exchange_invalid)} invalid rates")

# ============================================================
# STEP 5: Export cleaned datasets + validation report
# ============================================================
with open(f"{OUTPUT_DIR}/supplier_prices_clean.json", "w") as f:
    json.dump(supplier_clean, f, indent=2, ensure_ascii=False)

with open(f"{OUTPUT_DIR}/quotations_clean.json", "w") as f:
    json.dump(quotations_clean, f, indent=2, ensure_ascii=False)

with open(f"{OUTPUT_DIR}/exchange_rates_clean.json", "w") as f:
    json.dump(exchange_clean, f, indent=2, ensure_ascii=False)

validation_report = {
    "supplier_prices": {
        "valid": len(supplier_clean),
        "invalid": len(supplier_invalid),
        "invalid_rows": supplier_invalid,
    },
    "quotations": {
        "valid": len(quotations_clean),
        "invalid": len(quotations_invalid),
        "invalid_rows": quotations_invalid,
    },
    "exchange_rates": {
        "valid": len(exchange_clean),
        "invalid": len(exchange_invalid),
        "invalid_rows": exchange_invalid,
    },
}

with open(f"{OUTPUT_DIR}/validation_report.json", "w") as f:
    json.dump(validation_report, f, indent=2, ensure_ascii=False)

print("\n" + "=" * 50)
print("✅ Cleaned datasets saved:")
print(f"   - {OUTPUT_DIR}/supplier_prices_clean.json")
print(f"   - {OUTPUT_DIR}/quotations_clean.json")
print(f"   - {OUTPUT_DIR}/exchange_rates_clean.json")
print(f"   - {OUTPUT_DIR}/validation_report.json  (full list of flagged rows)")
print("\nNext: 05_export_json.ipynb merges these into the final clean_data.json")