# -*- coding: utf-8 -*-
"""05_export_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJqAMwxTqt2p8BZpzlkBIg_Wf2k60ZhU
"""

# -*- coding: utf-8 -*-
"""05_export_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/REPLACE_WITH_YOUR_COLAB_ID
"""

# ============================================
# 05_export_json.ipynb
# Merges cleaned supplier, quotation, and exchange rate data
# into a single unified clean_data.json for the AI agents
# ============================================

from google.colab import drive
drive.mount('/content/drive')

import os
import json
from datetime import datetime, timezone

# --- Setup shared project directory ---
PROJECT_ROOT = "/content/drive/MyDrive/project"
OUTPUT_DIR = f"{PROJECT_ROOT}/output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- Step 1: Load the cleaned datasets produced by 04_clean_validate.ipynb ---
def load_json(filename):
    path = f"{OUTPUT_DIR}/{filename}"
    if not os.path.exists(path):
        raise SystemExit(f"❌ Required input not found: {path}\n"
                          f"   Run 04_clean_validate.ipynb first.")
    with open(path, "r") as f:
        return json.load(f)

supplier_clean = load_json("supplier_prices_clean.json")
quotations_clean = load_json("quotations_clean.json")
exchange_clean = load_json("exchange_rates_clean.json")

print(f"Loaded {len(supplier_clean)} supplier rows, "
      f"{len(quotations_clean)} quotation records, "
      f"{len(exchange_clean)} exchange rates")

# ============================================================
# STEP 2: Build lookup helpers
# ============================================================

# Exchange rate lookup: (base, target) -> rate
rate_lookup = {
    (rec["base_currency"], rec["target_currency"]): rec["exchange_rate"]
    for rec in exchange_clean
}


def convert_to_inr(amount, currency):
    """Convert an amount to INR using available exchange rates. Returns None if no rate found."""
    if amount is None:
        return None
    if currency == "INR":
        return round(amount, 2)
    rate = rate_lookup.get((currency, "INR"))
    if rate is None:
        return None
    return round(amount * rate, 2)


# Supplier lookup keyed by (material, supplier) so quotations can be
# enriched with current lead time / MOQ / stock from the live price sheet.
supplier_lookup = {}
for rec in supplier_clean:
    key = (rec["material"].strip().lower(), rec["supplier"].strip().lower())
    supplier_lookup[key] = rec

matched_count = 0

# ============================================================
# STEP 3: Enrich each quotation with supplier + currency-converted data
# ============================================================
enriched_quotations = []

for q in quotations_clean:
    key = (q["material"].strip().lower(), (q["supplier"] or "").strip().lower())
    supplier_match = supplier_lookup.get(key)
    if supplier_match:
        matched_count += 1

    enriched_quotations.append({
        "source_file": q["source_file"],
        "customer": q["customer"],
        "material": q["material"],
        "supplier": q["supplier"],
        "quantity": q["quantity"],
        "quantity_unit": q["quantity_unit"],
        "unit_price": q["unit_price"],
        "currency": q["currency"],
        "unit_price_inr": convert_to_inr(q["unit_price"], q["currency"]),
        "transportation": q["transportation"],
        "packaging": q["packaging"],
        "gst_percent": q["gst_percent"],
        "total_cost": q["total_cost"],
        "total_cost_inr": convert_to_inr(q["total_cost"], q["currency"]),
        "delivery_time": q["delivery_time"],
        # Enrichment from the live supplier sheet, if a match was found
        "current_lead_time": supplier_match["lead_time"] if supplier_match else None,
        "current_moq": supplier_match["moq"] if supplier_match else None,
        "current_stock": supplier_match["available_stock"] if supplier_match else None,
        "supplier_price_matched": supplier_match is not None,
    })

print(f"\n✅ Enriched {len(enriched_quotations)} quotations "
      f"({matched_count} matched against current supplier sheet)")

# ============================================================
# STEP 4: Assemble the unified dataset
# ============================================================
clean_data = {
    "metadata": {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "quotation_count": len(enriched_quotations),
        "supplier_price_count": len(supplier_clean),
        "exchange_rate_count": len(exchange_clean),
    },
    "quotations": enriched_quotations,
    "supplier_prices": supplier_clean,
    "exchange_rates": exchange_clean,
}

# ============================================================
# STEP 5: Export clean_data.json
# ============================================================
output_path = f"{OUTPUT_DIR}/clean_data.json"
with open(output_path, "w") as f:
    json.dump(clean_data, f, indent=2, ensure_ascii=False)

print(f"\n✅ Saved unified dataset to {output_path}")
print(f"   - {len(enriched_quotations)} quotations")
print(f"   - {len(supplier_clean)} supplier price rows")
print(f"   - {len(exchange_clean)} exchange rates")

# ============================================================
# STEP 6 (OPTIONAL): Insert into PostgreSQL instead of / in addition to JSON
# ============================================================
# Uncomment and fill in your connection details if your team wants a DB
# instead of a flat file. Requires: !pip install psycopg2-binary
#
# import psycopg2
# from psycopg2.extras import Json
#
# conn = psycopg2.connect(
#     host="YOUR_HOST",
#     dbname="YOUR_DB",
#     user="YOUR_USER",
#     password="YOUR_PASSWORD",
# )
# cur = conn.cursor()
# cur.execute("""
#     CREATE TABLE IF NOT EXISTS clean_data (
#         id SERIAL PRIMARY KEY,
#         generated_at TIMESTAMPTZ,
#         payload JSONB
#     )
# """)
# cur.execute(
#     "INSERT INTO clean_data (generated_at, payload) VALUES (%s, %s)",
#     (clean_data["metadata"]["generated_at"], Json(clean_data)),
# )
# conn.commit()
# cur.close()
# conn.close()
# print("✅ Inserted clean_data into PostgreSQL")

print("\n🎉 Pipeline complete. clean_data.json is ready for the Knowledge Agent, "
      "Market Intelligence Agent, and Supervisor Agent to consume.")